Problem: Adding chain-maind keys will not be actually stored in disk …
crypto-org-chain/chain-main pull request #441
Opened 2021-03-31 07:31 UTC by leejw51crypto

Solution: add decoding _hexcode in service name fetched

2021-03-31 11:02 UTC, leejw51crypto commented
keyring pr is here
https://github.com/99designs/keyring/pull/83/files

2021-03-31 14:34 UTC, JayT106 commented
I see some of the modules been removed from the `go.sum`. How do they relate to the fixes?
For the keyring dependency, is it better to merge @leejw51crypto 's fixes to the upstream repo first and then use it? (Not sure how urgent is the fixes)

2021-04-01 01:22 UTC, tomtau commented
yeah, may be better to wait for the upstream -- it seems it's maintained

2021-04-01 02:00 UTC, leejw51crypto commented
> I see some of the modules been removed from the `go.sum`. How do they relate to the fixes?
> For the keyring dependency, is it better to merge @leejw51crypto 's fixes to the upstream repo first and then use it? (Not sure how urgent is the fixes)

i ran "go mod tidy" to check mod

this is urgent issue, because in linux,  keyring is not usable by default.

2021-04-12 06:42 UTC, tomtau requested changes
there are some conflicts with the latest master.

it seems upstream may take time -- I've forked the repo with the fix here, so the go.mod can be updated to this one: https://github.com/crypto-org-chain/keyring/tree/gnome for the moment

2021-04-20 10:01 UTC, leejw51crypto commented
ok, i'll rebase with the latest

2021-04-20 10:12 UTC, tomtau commented on go.mod
> +replace github.com/99designs/keyring => github.com/leejw51crypto/keyring v1.1.6-gnome
```suggestion
replace github.com/99designs/keyring => github.com/crypto-org-chain/keyring v1.1.6-gnome
```

2021-04-21 01:37 UTC, leejw51crypto commented
inspecting integration test failures

2021-04-21 03:29 UTC, leejw51crypto commented
fixed, increase waiting time twice :-)

2021-04-22 01:40 UTC, tomtau approved these changes

2021-04-22 01:40 UTC, merged

2021-09-01 03:21 UTC, matias904 requested changes
1150696e9218c9c6b615b3fdd0de1d1ccc8c1fbb