Add State Sync Script
crypto-org-chain/chain-main pull request #688
Opened 2021-12-13 05:16 UTC by faddat

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

Problem: State sync is hard

This PR adds scripts/statesync.bash, which will have a relay-optoimized state synced node running in seconds.  The goal of this commit is to allow relayers to run with the setup that I find ideal:

* State Synced
* RocksDB

In on order for rocksdb to work correctly, it replaces tecbot/gorocksdb with cosmos/gorocksdb.

It bumps the Tendermint version because .15 seems to do a bit better than .14.

# PR Checklist:

- [x] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [x] Have you rebased your work on top of the latest master? 
- [x] Have you checked your code compiles? (`make`)
- [x] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [x] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

2021-12-13 06:28 UTC, tomtau reviewed
thanks for the contribution! If I understand it correctly, the problem this is trying to solve is that the default build setup isn't ideal for high performance sentry nodes, is that correct? Could you perhaps open an issue that would have a more detailed problem description and link it here?

Once that's clearer, one thing to consider: why RocksDB and not BadgerDB? (BadgerDB should be supported too and it should be easier to build, given it's pure Go.)

Plus, if the problem is about the default build config, the solution for an alternative build script may be missing e.g. ldflags ( `-X github.com/cosmos/cosmos-sdk/types.DBBackend=...`): https://github.com/cosmos/cosmos-sdk/blob/52f6fc29da96339787da2048bb326b747a71c798/Makefile#L64

2021-12-13 07:00 UTC, faddat commented
@tomtau 

Basically, relay nodes across Cosmos -- Osmosis, Gaia, Terra and Cro in particular-- are hit with an unusual isssue.  Nodes used for relaying resemble sentries except that most sentries do not have very much inbound query traffic / tx writes.  Relay nodes have lots of both.

When the IBC network heats up, the node software is no longer able to sync and keep up to the tip of the chain. 

I imagine that you noticed that as the CRO chain gets longer, it gets less and less fast, while consuming more and more disk i/o bandwith, right?

Well, state sync is a way to remedy this issue because you've got only the tip of the chain.  Additionally, state sync makes it possible to -- no kidding -- validate gaia from a raspberry pi.  That's how much disk i/o consumption is reduced (I think by "shortening" the iavl tree, so there's less balancing to do.  So, when you've got a state synced node, another benefit is that it does far better in terms of query performance and writes.  

Typically, I'm in full support of 100% go solutions, but the reason for the ibc traffic jams is basically that relayers like us at Notional or the CROsNest team aren't able to keep nodes synced to the tip of the chain.  So far, my testing has shown that badgerdb is just a little bit faster than goleveldb for use on tendermint chains, while RocksDB is **much** faster, so this particular script is actually part of a devops deployment pattern we're building out at Notional to make our relay setup reproducible ("just add seed phrase") and much more performant than it currently is.  

Long-run, the team at valnodes has proposed:

https://twitter.com/valnodes/status/1466903567013449732?s=20

And I'm in full support of that effort but I figure it is at least a year out currently.

2021-12-13 07:24 UTC, tomtau requested changes
ok, could you add the missing parts for the rocksdb build: https://github.com/cosmos/cosmos-sdk/blob/52f6fc29da96339787da2048bb326b747a71c798/Makefile#L76 in the script?

2021-12-13 07:32 UTC, yihuang commented on scripts/statesync.bash
> +export CHAIN_MAIND_P2P_PERSISTENT_PEERS="87c3adb7d8f649c51eebe0d3335d8f9e28c362f2@seed-0.crypto.org:26656,e1d7ff02b78044795371beb1cd5fb803f9389256@seed-1.crypto.org:26656"
nice, I forgot we can override configs in this way.

2021-12-13 08:58 UTC, faddat commented
Happy to add the rocksdb config to the Makefile :).

2021-12-16 05:12 UTC, tomtau commented
there's a small conflict with the latest master -- @faddat could you rebase your PR after adding `-X github.com/cosmos/cosmos-sdk/types.DBBackend=rocksdb` or what else is needed in the build script?

2021-12-28 05:32 UTC, yihuang commented on go.mod
> +replace github.com/tecbot/gorocksdb => github.com/cosmos/gorocksdb v0.0.0-20211202124722-2c356d6d98e4
https://github.com/cosmos/cosmos-sdk/blob/master/db/go.mod#L36
cosmos-sdk use `v1.1.1`, should we follow suite here?

2021-12-28 05:33 UTC, yihuang commented on scripts/statesync.bash
> +go install -tags rocksdb ./...
One need to install the rocksdb c library by himself in advance, right?

2022-01-10 04:38 UTC, yihuang commented on scripts/statesync.bash
> +go install -tags rocksdb ./...
Do we also need the ldflat: `-X github.com/cosmos/cosmos-sdk/types.DBBackend=rocksdb`?

2022-01-27 02:41 UTC, tomtau commented
Closing this PR for now -- feel free to reopen it with the extra changes in Makefile

2022-01-27 02:41 UTC, closed without merging